# Generated by Django 3.1.7 on 2021-03-16 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favo4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favo4.content', verbose_name='コンテンツ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Favorite4',
            },
        ),
        migrations.CreateModel(
            name='PostTwi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favo4.chara', verbose_name='キャラ')),
                ('favorite4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='favo4.favorite4', verbose_name='F4')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'PostTwi',
            },
        ),
    ]
