# Generated by Django 3.1.7 on 2021-03-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favo4', '0003_auto_20210320_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chara',
            options={'verbose_name_plural': 'キャラ'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'コンテンツ'},
        ),
        migrations.AlterModelOptions(
            name='posttwi',
            options={'verbose_name_plural': 'マイページ'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'verbose_name_plural': 'サブクラス'},
        ),
        migrations.AlterField(
            model_name='content',
            name='copyright',
            field=models.CharField(default='©︎', max_length=100, verbose_name='権利表記'),
        ),
        migrations.AlterField(
            model_name='content',
            name='hashtag',
            field=models.CharField(default='#Favorite4', max_length=20, verbose_name='ハッシュタグ'),
        ),
    ]
