# Generated by Django 3.1.7 on 2021-03-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favo4', '0004_auto_20210320_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='flavor_text',
            field=models.CharField(default='私が好きなものは', max_length=30, verbose_name='フレーバーテキスト'),
        ),
    ]
